services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
    environment:
      PYTHONUNBUFFERED: "1"
      PAYLOAD_HOSTNAME: "localhost:8001"
      ENVIRONMENT: "production"
